version: '2'

services:
  node:
    image: node:10.6.0
    cached: true
    working_dir: /opt/app
    volumes:
      - ./:/opt/app

  firebase:
    build:
      dockerfile: Dockerfile.firebase
    cached: true
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    encrypted_env_file: ./.env.firebase.encrypted
